USE EyeCare;
INSERT INTO Images_Service (service_id,image_main, image_before, image_after) VALUES 
(1,'https://res.cloudinary.com/djmftornv/image/upload/v1739205202/services/kdott9s8w8idvtbx7egt.webp', 'https://res.cloudinary.com/djmftornv/image/upload/v1739205202/services/qumzwkoff4jluywc1d0q.jpg', 'https://res.cloudinary.com/djmftornv/image/upload/v1739205202/services/gc0xmzaookww3vzpcumw.jpg'),
(2,'https://res.cloudinary.com/djmftornv/image/upload/v1739202896/services/akpsjpuv2fliobtaondi.jpg', 'https://res.cloudinary.com/djmftornv/image/upload/v1739202896/services/nychyeayhtfpy03iwzpi.webp', 'https://res.cloudinary.com/djmftornv/image/upload/v1739202896/services/guwfekh4y75nm7fd9b1j.jpg'),
(3,'https://res.cloudinary.com/djmftornv/image/upload/v1739203204/services/wlcljzfjddwl5zaxkyff.jpg', 'https://res.cloudinary.com/djmftornv/image/upload/v1739203204/services/t0i3tfdalz7331pco8ni.jpg', 'https://res.cloudinary.com/djmftornv/image/upload/v1739203204/services/xvewilz7opufqddbeky7.jpg'),
(4,'https://res.cloudinary.com/djmftornv/image/upload/v1739205202/services/kdott9s8w8idvtbx7egt.webp', 'https://res.cloudinary.com/djmftornv/image/upload/v1739203420/services/ksts5vingscjkfcb2kyo.webp', 'https://res.cloudinary.com/djmftornv/image/upload/v1739203420/services/er0gqzr83c0fddjnkuys.webp'),
(5,'https://res.cloudinary.com/djmftornv/image/upload/v1739203778/services/nkpt6vnz0anm3xq7qjtl.webp', 'https://res.cloudinary.com/djmftornv/image/upload/v1739203778/services/tnbxvzzt4qzjsmebxcnk.jpg', 'https://res.cloudinary.com/djmftornv/image/upload/v1739203778/services/ptaf6afcos2tzhyk9wbq.webp'),
(6,'https://res.cloudinary.com/djmftornv/image/upload/v1739204168/services/xljnsboq5ekszvxezazh.webp', 'https://res.cloudinary.com/djmftornv/image/upload/v1739204168/services/asq99ylczjwf8aucro84.jpg', 'https://res.cloudinary.com/djmftornv/image/upload/v1739204168/services/euscer9hwv6majuwbflu.webp'),
(7,'https://res.cloudinary.com/djmftornv/image/upload/v1739204632/services/ggqklhevcybamipwlez9.webp', 'https://res.cloudinary.com/djmftornv/image/upload/v1739204633/services/ygqdrt88oiuja6xpw5pt.webp', 'https://res.cloudinary.com/djmftornv/image/upload/v1739204634/services/dztqjbwoqyl0n5gr6x5p.png'),
(8,'https://res.cloudinary.com/djmftornv/image/upload/v1739205319/services/emyiusn7y1sjdhunm7lq.jpg', 'https://res.cloudinary.com/djmftornv/image/upload/v1739205319/services/y4z20htqvo6tbr4mr354.jpg', 'https://res.cloudinary.com/djmftornv/image/upload/v1739205388/services/ornyacor7sptektygmxg.jpg'),
(9,'https://res.cloudinary.com/djmftornv/image/upload/v1739205445/services/dze1m3pjexm5wtdq8r0b.jpg', 'https://res.cloudinary.com/djmftornv/image/upload/v1739205445/services/zzw29un72je7ueuxlocf.jpg', 'https://res.cloudinary.com/djmftornv/image/upload/v1739205445/services/sfxeuc7pkctzjpgpyev4.jpg'),
(10,'https://res.cloudinary.com/djmftornv/image/upload/v1739205577/services/ygblvhe9i1nqppbehvnh.webp', 'https://res.cloudinary.com/djmftornv/image/upload/v1739205577/services/d1kn8ds8tifoxukscstt.jpg', 'https://res.cloudinary.com/djmftornv/image/upload/v1739205577/services/wsyolrrdif5jvmslo9jp.jpg'),
(11,'https://res.cloudinary.com/djmftornv/image/upload/v1739205715/services/pgvf7ieiwyaqjrzoztzp.jpg', 'https://res.cloudinary.com/djmftornv/image/upload/v1739205715/services/sjiabyg1if1yl3ilmyv9.jpg', 'https://res.cloudinary.com/djmftornv/image/upload/v1739205716/services/tbevvc43fce1dcdrwthm.png'),
(12,'https://res.cloudinary.com/djmftornv/image/upload/v1739205817/services/felgddbyjitl6bjgwlqv.webp', 'https://res.cloudinary.com/djmftornv/image/upload/v1739205817/services/vkywocm1osphsm5y8ipj.webp', 'https://res.cloudinary.com/djmftornv/image/upload/v1739205817/services/felgddbyjitl6bjgwlqv.webp');

INSERT INTO dbo.Banner (banner_name, banner_title, banner_description, banner_status, link_banner, href_banner) 
VALUES 
('banner1', N'Dịch vụ nhãn khoa từ Nhật Bản', N'Từ Nhật Bản, chúng tôi mang đến dịch vụ y tế tiêu chuẩn quốc tế với mong muốn mỗi bệnh nhân đều được trải nghiệm sự chăm sóc chu đáo, thăm khám và điều trị bằng những phương pháp tiên tiến nhất.', 'true', 'https://res.cloudinary.com/djmftornv/image/upload/v1738735993/banner/teig1usvmsnbavavbrck.jpg', 'trangchu'), 
('banner2', N'Thăm khám với Bác sỹ đầu ngành', N'Mọi bệnh nhân đều xứng đáng được điều trị bằng những phương pháp hiện đại, tối ưu nhất, chúng tôi hiểu và luôn nỗ lực vì điều đó.', 'true', 'https://res.cloudinary.com/djmftornv/image/upload/v1738736003/banner/fotnuc6q51rwhk9rkun5.jpg', 'trangchu'), 
('banner3', N'Công nghệ, thiết bị điều trị tiên tiến', N'Bởi hiểu rằng đôi mắt là cánh cửa kết nối chúng ta với thế giới xung quanh, nên chúng tôi luôn nỗ lực để mỗi bệnh nhân được tự do khám phá và tận hưởng trọn vẹn cuộc sống bằng đôi mắt sáng khỏe.', 'true', 'https://res.cloudinary.com/djmftornv/image/upload/v1738736134/banner/kqco2frqlx3kihljkqsn.png', 'trangchu'), 
('banner4', N'An yên tận hưởng tuổi xế chiều', N'Chúng tôi nỗ lực để cùng bệnh nhân lấy lại đôi mắt sáng khỏe ở tuổi xế chiều để họ an yên tận hưởng mọi khoảnh khắc của cuộc sống bởi chúng tôi tin rằng họ xứng đáng.', 'true', 'https://res.cloudinary.com/djmftornv/image/upload/v1738736297/banner/f2a8numr5n4n2om6xete.jpg', 'trangchu'), 
('banner5', N'Tự do khám phá thế giới', N'Bởi hiểu rằng đôi mắt là cánh cửa kết nối chúng ta với thế giới xung quanh, nên chúng tôi luôn nỗ lực để mỗi bệnh nhân được tự do khám phá và tận hưởng trọn vẹn cuộc sống bằng đôi mắt sáng khỏe.', 'true', 'https://res.cloudinary.com/djmftornv/image/upload/v1738736344/banner/zykj3oqa13kcskcluap3.jpg', 'trangchu'), 
('banner6', N'Tự do tận hưởng đam mê thể thao', N'Hãy để chúng tôi cùng bạn loại bỏ sự phiền toái của kính gọng hay kính áp tròng để tự do tham gia các môn thể thao yêu thích và tận hưởng mọi đam mê, sở thích.', 'true', 'https://res.cloudinary.com/djmftornv/image/upload/v1738736414/banner/xwa2ifvpyhwjpv2exvrr.jpg', 'trangchu');